---
####新加的内容
apiVersion: v1
kind: Secret
metadata:
  name: traefik-ingress-controller-default-cert
  namespace: kube-system
  labels:
    app: traefik
type: Opaque
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURWekNDQWorZ0F3SUJBZ0lKQU1wNjU4eXVmYXRKTUEwR0NTcUdTSWIzRFFFQkN3VUFNRUl4Q3pBSkJnTlYKQkFZVEFsaFlNUlV3RXdZRFZRUUhEQXhFWldaaGRXeDBJRU5wZEhreEhEQWFCZ05WQkFvTUUwUmxabUYxYkhRZwpRMjl0Y0dGdWVTQk1kR1F3SGhjTk1UZ3hNREkxTURNME5UQTJXaGNOTVRreE1ESTFNRE0wTlRBMldqQkNNUXN3CkNRWURWUVFHRXdKWVdERVZNQk1HQTFVRUJ3d01SR1ZtWVhWc2RDQkRhWFI1TVJ3d0dnWURWUVFLREJORVpXWmgKZFd4MElFTnZiWEJoYm5rZ1RIUmtNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQQp3ZVVyTjVnYnlDMHVQR3JHVFV2TVNiYUZCMlN4SVVmQzdBRXFKSExSL2VBTjNqWURMZEhraVI4bm5LTEhIU29PCjJVWjZLRnR5ejJ5RiszNUZFaXhnVTBxa2ZybkFoYzJCcDY1SmlHVXFMU09kNmZENnR0L3dIek9hU2JRRXkzZFEKU0M3ZGllcE5EeTNmRGdmdDNGc0wvdXFGL0tQYSsvVXpaUSs1d0NCdk1nL3FPMGRicW1OV2thZkV5ODNNc0VhaQpLQWkvWllBZVkxOFFZSGowQzJ6Z3dVLzZyRW5PeU9jT2xYV1o5bmY0K3RJdUF1ZzEwMlB5cEZFQlBsVXc0RmhXCnUzcU5rZkJJbEJabnVXUXg5UXNydUphdHl1VDQwaWJBQmpUTFBzOE9OZFFDNHQ3QWRhcTVHbkhHWGVoaTZ2dTMKdkJiTEM3TFBUMDJadHBTUngzUHFld0lEQVFBQm8xQXdUakFkQmdOVkhRNEVGZ1FVa3R4TEc5SmdVMmVmOGFQbgpCOGJRZ0laYzU2a3dId1lEVlIwakJCZ3dGb0FVa3R4TEc5SmdVMmVmOGFQbkI4YlFnSVpjNTZrd0RBWURWUjBUCkJBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQW9qRUpxTElMb0VNNkVIQldRMXpmM2RQbFVJbmMKai9iT0pKMFdobi9vemt6LzkrNFV6OFlTT0prRTFWSG1IQU8xK0JZNGVhVVZzNVZ2ZWZROC9sUWhuV1RFYkFQKwpUVktucjVpS1BaT2JrTWpPb2RuS1BWbVJHaStKWnA0U3doS1l2NTl5ZlZNQUNtdGE3TE4vVUZFQXBhcXVTZkZnCnNGNkw4SmNuVUdhcGVoeFVDYmhlMDhPMmJwdVlRRnVLZzlMZDBHZi9pY1ZCb2Fra0ZIeUJBM3kyL2owdnIrK2YKd3lBUHFydWo0TnAvOFcyc3pXZGtVQy83ZzhNZG0yU0YrZWJIYmVneGwvblJoY0JXNlNCK01ZM0pqbXJGYXAxaQo0QmRpSlVRdUl3UFR4WVg3UTNRZDk2UlFhNVpyNUhCcE5lWFQzeldZM1k0SUJSZlFST1RaNlFTMy9nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV3QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktvd2dnU21BZ0VBQW9JQkFRREI1U3MzbUJ2SUxTNDgKYXNaTlM4eEp0b1VIWkxFaFI4THNBU29rY3RIOTRBM2VOZ010MGVTSkh5ZWNvc2NkS2c3WlJub29XM0xQYklYNwpma1VTTEdCVFNxUit1Y0NGellHbnJrbUlaU290STUzcDhQcTIzL0FmTTVwSnRBVExkMUJJTHQySjZrMFBMZDhPCkIrM2NXd3YrNm9YOG85cjc5VE5sRDduQUlHOHlEK283UjF1cVkxYVJwOFRMemN5d1JxSW9DTDlsZ0I1alh4QmcKZVBRTGJPREJUL3FzU2M3STV3NlZkWm4yZC9qNjBpNEM2RFhUWS9La1VRRStWVERnV0ZhN2VvMlI4RWlVRm1lNQpaREgxQ3l1NGxxM0s1UGpTSnNBR05Ncyt6dzQxMUFMaTNzQjFxcmthY2NaZDZHTHErN2U4RnNzTHNzOVBUWm0yCmxKSEhjK3A3QWdNQkFBRUNnZ0VCQUxDdXFqWHJwbzAvRmwyNWtsL0hEUzJ5WXdBOHNlZTRvNWM0N0hUd0tBZ20KVFp6S0xSVm9xTTZHbENyNGJXWlc5OWJua05NTG1kQUhmUU9ScVZFSkhQRnBHQUhlTTkvNVJ3ZE1HdmR0OEFQWAo2OExNY3ptSFVDQ3VmZzVoT3VsSkhOL1p6TWdxdC9ONEFrU2YxeEN2Nm50c3E1RnVvbEpydWx5Qit1cG00OHlCCisxTGNGcFlnZ0lLdGRYeCtEWG41dHRURnRDSEpJMVdUNHViQkVSZWR3TG52SCsvbS9ROVlqVC9LUC9yN1h1K2sKNVhzTC9XaHZRM0NHZGxpTVU3eS8wbktrWWxMaHd2R3J4d3p0K3ZPLzNLRXFhYUMwcmlaNTdmTnp1K0FOUnFZZApxZmVRYUNaQVRod1ZxREhjV2dVNk90Rk9kUDdzOGZETzZZeHh0VHlzOFVrQ2dZRUE3SlZRbUFHNkZoRjZCL29mClJIUC9qQWZUK3BFSlN6YU95Q2c3S0VOMjZ4a1pESUxFRXpOZno5SmlXd2NEV0xQWVpOdXVxd0ZKRzErUXgrS08KNUM5QzYzZ0YrUC9BaUxBeUQwRmpYWU10cFc4NDlTRlgrTkVKQVRHR1lseGRTMTgxOStBL2VLVkVnd1ovOWRWUwpnUXJIMGVJSlk4RGp5MnBwRnN1VWF6bEh0TDhDZ1lFQTBjNzNBSis4V3ZESWI5VnE0UUZWaXNxdDFNaDVGV0JlCmkxQWozdFpIZDF6RzhKRWpPQ0pNUzYwdlY1WmlWYndwd3kreW1SS0R1cjIrbnhIcmNvQWZWRUFSMEY2MkFLWHUKdmZ3QUlKbVZNbTc1T0ROekh4OEVFT1lhblVDWDdWKy91VDFaVmNCeEtxYnQ3eE1KVHNQaEQ0WnlZNmZKMGZ3UQpKemYrWWEwdGpVVUNnWUVBbUdkUHRieFhEZVJRUWxkRVVTcVFrcnB3T2RlNHJ2VUVZYmhZODRVU1ZEeWt3RVIwCjN4R1hSUjk0TUwrQnptQjhvK3hJeHV4YkZnRW9HVHUvWlF0MUJvOFkrZUIzUFJhVUNQUE1lTzhLTnFwQmZOZnYKL2Q5YTk2UFp0LzljTWpPeFptN1ZOSGp5ZTUxeVRRRVExd1FFMlJYTmlxODFqMUtMUkIzOURGMm43YTBDZ1lFQQpoOWM0bFc3V3hRcWd1OGV5SzN4eHBpc1Q0WERxOUt3d2lvS1l0dTZGMXdKNnk4Y3N4bXR1ZXBEbTFnN0lIRHAzCno2aFNPa21DZ0tYWmhhUlVqUTNuT3VWQW8yaXU3anlCRndEU0ZFbGNFQXRKME5sKzcrZGsrb3dCTDA5akRvMnYKMUgra0Y2RkJwQnZ3Y1pvaHJKMm1XaWJ5YVJONTJEc2JPa2xHcW5jMXh3RUNnWUVBc004SEcxcWR0OTR5RWI2egpkT3pNVVBsTkgrWXVES3RLNXYvck1PZ1ovbW1VSGxtVGE5aFptUUJFczFweE0vbjRGaTNEY1NUUEpSRklFYmxrClFFQkxDdE9LMGxFNlF6SDRzUVBSV2lqNjdDVm5ZYjQ0Rmp0bnIwbXpVSTh2T1J6d04vQjIreG1rK1dRK0JwdGUKQldaWThDblFCa0haZk01Nmd3bXZ6QlhXenMwPQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
---
###配置https重定向,哪些应用需要http访问，端口必须写入下面
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-ingress-controller-config-map
  namespace: kube-system
  labels:
    app: traefik
data:
  traefik.toml: |+
    logLevel = "INFO"
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
          certFile = "/ssl/tls.crt"
          keyFile = "/ssl/tls.key"
      [entryPoints.traefik]
      address = ":8080"
      [entryPoints.nginx]
      address = ":8000"
     [kubernetes]
     [traefikLog]
          format = "json"
     [api]
          entryPoint = "traefik"
          dashboard = true
---
## 新加的内容结束



kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
- kind: ServiceAccount
  name: traefik-ingress-controller
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:v1.7.2
        imagePullPolicy: IfNotPresent
        name: traefik-ingress-lb
#修改了之前的内容
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /ssl
          name: ssl
        - mountPath: /etc/localtime
          name: time
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          hostPort: 443
          protocol: TCP
        - name: traefik-web
          containerPort: 8080
          hostPort: 8080
          protocol: TCP
        args:
        - --configfile=/config/traefik.toml
      volumes:
      - name: config
        configMap:
          name: traefik-ingress-controller-config-map
      - name: ssl
        secret:
          secretName: traefik-ingress-controller-default-cert
      - name: time
        hostPath:
          path: /etc/localtime
# 修改结束
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      # 该端口为 traefik ingress-controller的服务端口
      port: 80
      # 集群hosts文件中设置的 NODE_PORT_RANGE 作为 NodePort的可用范围
      # 从默认20000~40000之间选一个可用端口，让ingress-controller暴露给外部的访问
      nodePort: 23456
      name: web
    - protocol: TCP
      # 该端口为 traefik 的管理WEB界面
      port: 8080
      name: admin
  type: LoadBalancer
#  externalIPs: 
#    - 172.17.100.232
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: kube-system
spec:
  tls:
  - secretName: traefik-ingress-controller-default-cert
  rules:
  - host: jtcf.ingress.com
    http:
      paths:
      - path: /
        backend:
          serviceName: traefik-ingress-service
          servicePort: 8080
