apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
#  type: NodePort
 ports:
 - port: 80
   targetPort: 80
   protocol: TCP
   name: http
#    nodePort: 30088
 selector:
   tier: nginx
 externalIPs:
  - 172.17.100.232
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: nginx
  template:
    metadata:
      labels:
        tier: nginx
    spec:
      containers:
        - name: nginx
#          image: 172.17.100.231:5000/nginx:1.12
          image: 172.17.100.231:5000/nginx-php
          imagePullPolicy: IfNotPresent    ####优先使用本地镜像
          ports:
            - containerPort: 80
          resources:
           requests:
             cpu: "10m"
             memory: "200Mi"
           limits:
             cpu: "50m"
             memory: "500Mi"
          volumeMounts:
            - name: nginx3conf
              mountPath: /etc/nginx
            - name: nginx2html
              mountPath: /usr/share/nginx/html
            - name: nginxlog
              mountPath: /var/log/nginx
      volumes:
        - name: nginx3conf
          nfs:
            server: 172.17.100.233
            path: /data/nfs
        - name: nginx2html
          nfs:
            server: 172.17.100.233
            path: /data/nfs/html 
        - name: nginxlog
#          nfs:
#            server: 172.17.100.233
#            path: /data/nfs
          persistentVolumeClaim:
            claimName: pvc0002
#      nodeSelector:
#          role: mysqlnode
