{
 "title": "Kubernetes Cluster Health (Prometheus)",
 "description": "Kubernetes Cluster Health (Prometheus)",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Control Plane Components Down",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=~\"apiserver|kube-scheduler|kube-controller-manager\"} == 0)"
    }
   ]
  },
  {
   "title": "Node Disk Pressure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Unschedulable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)"
    }
   ]
  },
  {
   "title": "Node Memory Pressure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Crashlooping Pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts[1h]) > 5)"
    }
   ]
  },
  {
   "title": "Node Not Ready",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"})"
    }
   ]
  },
  {
   "title": "Alerts Firing",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  {
   "title": "Alerts Pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"pending\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  }
 ]
}